public class apexExample5 {
    public string pageBlockTitle{set;get;}
    public string sectionTitle{set;get;}
    public string subtitle{set;get;}
    public string help{set;get;}
    public string direction{set;get;}
    public string body{set;get;}
    public apexExample5(){
        pageBlockTitle='Student Example';
            sectionTitle='Apex ClassEx';
            subtitle='Apex classEX2';
            help='/apex/page1';
            direction='LTR';
            body='data captured from apexExample class';
    }   

}