public class JSONDEBUGCODES {
   /* Getting tokens
     string jsonString='{"Name":"kiran","Age":30}';
system.JSONParser jp=JSON.createParser(jsonString);
Integer age;
while(jp.nextToken()!=null){
    system.debug(jp.getCurrentToken());
    system.debug(jp.getText());
}
system.debug(age);

Deserialize untyped(seperating keys and values and printing)
string js='{"Name":"Kiran","Age":30}';
Map<string,object>result=(Map<string,object>)JSON.deserializeUntyped(js);
system.debug(result.keyset());
system.debug(result.values());

*/


}